name: Build and Deploy WAR to Tomcat

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build WAR with Maven
        run: |
          mvn clean package -DskipTests
          ls -la target/  # Kiểm tra file trong target

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target

      - name: Set up Tomcat
        run: |
          wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
          tar -xzf apache-tomcat-10.1.24.tar.gz
          mv apache-tomcat-10.1.24 tomcat

      - name: Deploy WAR to Tomcat
        run: |
          cp target/*.war tomcat/webapps/
          chmod +x tomcat/bin/*.sh
          tomcat/bin/startup.sh

      - name: Wait for Tomcat to start
        run: sleep 20

      - name: Check Deployment
        run: curl http://localhost:8080/your-app/