name: Build, Test, and Deploy WAR to Tomcat

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Enable PowerShell script execution
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        shell: pwsh

      - name: Run Unit Tests
        run: mvn test

      - name: Build WAR with Maven
        run: |
          mvn clean package -DskipTests
          dir target/

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/demo.war

  deploy:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: target

      - name: Debug Paths
        run: |
          dir C:\Tomcat\apache-tomcat-10.1.42-windows-x64\apache-tomcat-10.1.42
          dir target\demo.war

      - name: Deploy WAR to Tomcat
        run: |
          if not exist C:\Tomcat\apache-tomcat-10.1.42-windows-x64\apache-tomcat-10.1.42\webapps\ mkdir C:\Tomcat\apache-tomcat-10.1.42-windows-x64\apache-tomcat-10.1.42\webapps\
          copy target\demo.war C:\Tomcat\apache-tomcat-10.1.42-windows-x64\apache-tomcat-10.1.42\webapps\
          C:\Tomcat\apache-tomcat-10.1.42-windows-x64\apache-tomcat-10.1.42\bin\startup.bat

      - name: Wait for Tomcat to start
        run: timeout /t 20

      - name: Check Deployment
        run: |
          curl http://localhost:8080/demo/
        continue-on-error: true